version: '3'
services:
  serposcope:
    build:
      context: ./
      dockerfile: ./serposcope/Dockerfile
      args:
        UBUNTU_DOCKER_IMAGE: ${UBUNTU_DOCKER_IMAGE}
        SERPOSCOPE_VERSION: ${SERPOSCOPE_VERSION}
        CPU_MODEL: ${CPU_MODEL}
        APP_USER: ${APP_USER}
        APP_GROUP: ${APP_GROUP}
    container_name: ${WEB_SERVICE_HOST}
    hostname: '${WEB_SERVICE_HOST}'
    ports:
      - '${WEB_SERVICE_PORT}:${WEB_SERVICE_PORT}'
    command: sh -c '/entrypoint.sh'
    networks:
      - nginxproxy_default
    restart: always
  nginx:
    image: nginx
    container_name: ${EDGE_SERVICE_HOST}
    hostname: '${EDGE_SERVICE_HOST}'
    depends_on:
      - serposcope
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    extra_hosts:
      - '${WEB_SERVICE_HOST}:${SERVER_IP}'
    environment:
      VIRTUAL_HOST: ${SERVICE_HOST}
      LETSENCRYPT_HOST: ${SERVICE_HOST}
      LETSENCRYPT_EMAIL: ${EMAIL}
      APP_PORT: ${WEB_SERVICE_PORT}
      APP_HOST: ${WEB_SERVICE_HOST}
      ALLOWED_IP: ${ALLOWED_IP}
      CERT_NAME: ${CERT_NAME}

    command: /bin/sh -c "envsubst '$$VIRTUAL_HOST$$APP_PORT$$APP_HOST$$ALLOWED_IP' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      nginxproxy_default:
    restart: always

networks:
  nginxproxy_default:
    external: true
